// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sapa.DAL;

namespace Sapa.DAL.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200412113136_def value")]
    partial class defvalue
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sapa.DAL.Models.Builder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActivityStartDate")
                        .HasColumnName("activitystartdate")
                        .HasColumnType("datetime");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("address")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BIN")
                        .IsRequired()
                        .HasColumnName("BIN")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("isdeleted")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Builder");

                    b.ToTable("Builders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityStartDate = new DateTime(2020, 4, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Address = "Yrghyz 11",
                            BIN = "1234-4567-7894-1236",
                            IsDeleted = false,
                            Name = "BI Group"
                        });
                });

            modelBuilder.Entity("Sapa.DAL.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("address")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BuilderId")
                        .HasColumnType("int");

                    b.Property<int>("Floors")
                        .HasColumnName("floors")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnName("height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("isdeleted")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Price")
                        .HasColumnName("price")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Building");

                    b.HasIndex("BuilderId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Imanbayeva",
                            BuilderId = 1,
                            Floors = 20,
                            Height = 100,
                            IsDeleted = false,
                            Name = "Shanyrak",
                            Price = 150000
                        });
                });

            modelBuilder.Entity("Sapa.DAL.Models.Building", b =>
                {
                    b.HasOne("Sapa.DAL.Models.Builder", "Builder")
                        .WithMany("Buildings")
                        .HasForeignKey("BuilderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
